language: d

d:
    - dmd

os:
    - linux
    - windows
    - osx

script:
    - dub test --compiler=${DC} --build-mode=singleFile
    - dub test --compiler=${DC} --build-mode=singleFile -c vanilla
    - dub test --compiler=${DC} --build-mode=singleFile -c colours
    - dub test --compiler=${DC} --build-mode=singleFile -c colours+webtitles
    - dub build -b plain --compiler=${DC} --build-mode=singleFile
    - dub build -b plain --compiler=${DC} --build-mode=singleFile -c vanilla
    - dub build -b plain --compiler=${DC} --build-mode=singleFile -c colours
    - dub build -b plain --compiler=${DC} --build-mode=singleFile -c colours+webtitles
