language: d

d:
    - dmd

os:
    - linux
    - windows

script:
    - dub test --compiler=${DC} --build-mode=singleFile
    - dub test --compiler=${DC} --build-mode=singleFile -c nocolours
    - dub test --compiler=${DC} --build-mode=singleFile -c nowebtitles-nocolours
    - dub build -b plain --compiler=${DC} --build-mode=singleFile
    - dub build -b plain --compiler=${DC} --build-mode=singleFile -c nocolours
    - dub build -b plain --compiler=${DC} --build-mode=singleFile -c nowebtitles-nocolours
