language: d

d:
    - dmd

os:
    - linux
    - windows

script:
    - dub test --parallel --compiler=${DC} --build-mode=singleFile
    - dub test --parallel --compiler=${DC} --build-mode=singleFile -c vanilla
    - dub test --parallel --compiler=${DC} --build-mode=singleFile -c colours
    - dub test --parallel --compiler=${DC} --build-mode=singleFile -c webtitles
    - dub test --parallel --compiler=${DC} --build-mode=singleFile -c colours+webtitles
    - dub build -b plain --parallel --compiler=${DC} --build-mode=singleFile
    - dub build -b plain --parallel --compiler=${DC} --build-mode=singleFile -c vanilla
    - dub build -b plain --parallel --compiler=${DC} --build-mode=singleFile -c colours
    - dub build -b plain --parallel --compiler=${DC} --build-mode=singleFile -c webtitles
    - dub build -b plain --parallel --compiler=${DC} --build-mode=singleFile -c colours+webtitles
