language: d

d:
    - dmd

os:
    - linux
    - windows

script:
    - dub test --compiler=${DC}
    - dub test --compiler=${DC} -c nocolours
    - dub test --compiler=${DC} -c nowebtitles-nocolours
    - dub build -b plain --compiler=${DC}
    - dub build -b plain --compiler=${DC} -c nocolours
    - dub build -b plain --compiler=${DC} -c nowebtitles-nocolours
