language: d

sudo: required
dist: bionic

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  #- git clone https://github.com/zorael/lu.git
  #- git clone https://github.com/zorael/dialect.git
  #- dub add-local lu
  #- dub add-local dialect
  - time dub test  --compiler=${DC} # unittest already includes more than other configs
  - time dub test  --compiler=${DC} --nodeps --force -c vanilla
  - time dub build --compiler=${DC} --nodeps --force -b debug   -c vanilla
  #- time dub build --compiler=${DC} --nodeps --force -b debug   -c full
  - time dub build --compiler=${DC} --nodeps --force -b debug   -c dev
  - time dub build --compiler=${DC} --nodeps --force -b plain   -c vanilla || true
  #- time dub build --compiler=${DC} --nodeps --force -b plain   -c full  || true
  - time dub build --compiler=${DC} --nodeps --force -b plain   -c dev  || true
  - time dub build --compiler=${DC} --nodeps --force -b release -c vanilla || true
  #- time dub build --compiler=${DC} --nodeps --force -b release -c full || true
  - time dub build --compiler=${DC} --nodeps --force -b release -c dev  || true

before_deploy:
  #- time dub build --compiler=${DC} --nodeps --force -b ddox
  - cd ..
  - git clone https://github.com/adamdruppe/adrdox.git
  - cd adrdox
  - make
  - ./doc2 -ip --directory ../kameloso/docs ../kameloso
  - cd ../kameloso
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch:
      - master
      - /travis-.*/
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
