language: d

sudo: required
dist: trusty

d:
  - dmd
  - ldc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libevent-dev

script:
  - dub test --compiler=${DC} -c vanilla
  - dub test --compiler=${DC} -c colours+web
  - dub build -b plain --compiler=${DC} -c vanilla
  - dub build -b plain --compiler=${DC} -c colours+web
  - dub build -b ddox --compiler=${DC} -c colours+web

deploy:
  local_dir: docs
  file:
    - .circleci/config.yml
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
  cache:
    directories:
      - $HOME/.dub

after_deploy:
  - echo DC ${DC}
  - echo Creating .circleci
  - mkdir -p .circleci
  - if [ -e .circleci/config.yml ]; then echo EXISTS; fi
  - echo Creating config.yml
  - echo -e "general:\n  branches:\n    ignore:\n      gh-pages" > .circleci/config.yml
