language: d

sudo: required
dist: bionic

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - dub test  --compiler=${DC} # unittest already includes more than other configs
  - dub test  --compiler=${DC} --nodeps -c vanilla
  - dub build --compiler=${DC} --nodeps -b debug   -c dev
  - dub build --compiler=${DC} --nodeps -b debug   -c vanilla
  - dub build --compiler=${DC} --nodeps -b plain   -c dev  || true
  - dub build --compiler=${DC} --nodeps -b plain   -c vanilla || true
  - dub build --compiler=${DC} --nodeps -b release -c dev  || true
  - dub build --compiler=${DC} --nodeps -b release -c vanilla || true

before_deploy:
  - dub fetch ddox
  - test ! -e "$HOME/.dub/packages/ddox-0.16.13" || sed -i "s/import std.conv;/public \0/" "$HOME/.dub/packages/ddox-0.16.13/ddox/source/ddox/api.d"
  - dub build --compiler=${DC} --nodeps -b ddox -c pluginless-vanilla
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
