version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install compilers
          command: ./.circleci/run.sh install-deps
      - run:
          name: Build (dub)
          command: ./.circleci/run.sh build
      - store_artifacts:
          path: ./artifacts

