version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Install compilers
          command: ./.circleci/run.sh install-deps
      - run:
          name: Build (dub)
          command: ./.circleci/run.sh build

